config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#top'
  get 'home/about' => 'users#about', as: 'about_book'
  devise_for :users, controllers: {sessions: 'devise/sessions', 
  	registrations: 'devise/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:new, :create, :index, :show, :edit, :update]
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name,uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}

  def email_required?
  	false
  end

  def email_changed?
  	false
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, {only: [:index, :show, :edit, :update]}
  before_action :correct_user, {only: [:edit, :update]}

  def top
  end

  def about
  end

  def new
  	@user = User.new
  end

  def index
  	@users = User.all
  	@book = Book.new
  	@user = current_user
  end

  def show
  	@user = User.find(params[:id])
  	@book = Book.new
  	@books = @user.books
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  	  flash[:notice] = "You have updated user successfully."
  	    redirect_to user_path(@user.id)
  	else
  	  render "edit"
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/about.html.erb
<h1>
	Welcome to Bookers!
</h1>

app/views/users/edit.html.erb
<h2>User info</h2>
<div class="error-box">
    <% if @user.errors.any? %>
      <div class="error-explain">
        <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li>
             <%= message %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
</div>

<%= form_for(@user) do |f| %>
  <h4>Name</h4>
  <%= f.text_field :name %>

  <h4>Image</h4>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>

  <h4>Introduction</h4>
  <%= f.text_area :introduction %>
  <p><%= f.submit 'Update User' %></p>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
   <div class="col-xs-3">
    <h1>User info</h1>
     <%= attachment_image_tag @user, :profile_image, :fill, 60,60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
     <table class="table">
       <tbody>
         <tr>
           <th>
             name
           </th>
           <th>
             <%= @user.name %>
           </th>
         </tr>
         <tr>
           <th>
             introduction
           </th>
           <th>
             <%= @user.introduction %>
           </th>
         </tr>
       </tbody>
     </table>
     <div class="row">
       <% if @user.id == current_user.id %>
           <%= link_to "", edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
       <% else %>
           <%= link_to "", user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
       <% end %>
     </div>


    <h1>New book</h1>
     <%= form_for(@book) do |f| %>
       <h4>Title</h4>
       <%= f.text_field :title %>

       <h4>Opinion</h4>
       <%= f.text_area :body %>

       <%= f.submit 'Create Book', class: "btn btn-primary btn-lg" %>
     <% end %>
   </div>
   <div class="col-xs-9">
   <h1>Users</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th align="left">image</th>
          <th align="left">name</th>
          <th colspan="1" align="left"></th>
        </tr>
      </thead>
      <tbody>
       <% @users.each do |user| %>
        <tr>
          <td>
           <%= attachment_image_tag user, :profile_image, :fill, 60,60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
          </td>
          <td>
           <%= user.name %>
          </td>
          <td>
            <%= link_to "Show", user_path(user.id) %>
          </td>
        </tr>
       <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
   <div class="flash">
    <%= flash[:notice] %>
   </div>
<% end %>




<div class="container">
  <div class="row">
   <div class="col-xs-3">
    <h1>User info</h1>
     <%= attachment_image_tag @user, :profile_image, :fill, 60,60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
     <table class="table">
       <tbody>
         <tr>
           <th>
             name
           </th>
           <th>
             <%= @user.name %>
           </th>
         </tr>
         <tr>
           <th>
             introduction
           </th>
           <th>
             <%= @user.introduction %>
           </th>
         </tr>
       </tbody>
     </table>
     <div class="row">
       <% if @user.id == current_user.id %>
           <%= link_to "", edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
       <% else %>
           <%= link_to "", user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
       <% end %>
     </div>

    <h1>New book</h1>
     <%= form_for(@book) do |f| %>
       <h4>Title</h4>
       <%= f.text_field :title %>

       <h4>Opinion</h4>
       <%= f.text_area :body %>

       <%= f.submit 'Create Book', class: "btn btn-primary btn-lg" %>
     <% end %>
   </div>

   <div class="col-xs-9">
   <h1>Books</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th align="left" colspan="1"></th>
          <th align="left">Title</th>
          <th align="left">Opinion</th>
        </tr>
      </thead>
      <tbody>
       <% @books.each do |book| %>
        <tr>
          <td><%= attachment_image_tag book.user, :profile_image, :fill, 60,60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %></td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
        </tr>
       <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>

app/views/users/top.html.erb
<div class="container">
	<% if flash[:notice] %>
       <div class="flash">
        <%= flash[:notice] %>
       </div>
    <% end %>
    <div class="row">
    	<div class="top-message col-md-offset-3 col-md-6">
    		<h1>
    			welcome to
    			<span class="glyphicon glyphicon-book">
    				<strong>Bookers</strong>
    				!!
    			</span>
    		</h1>
    		<p>
    			In
    			<span class="glyphicon glyphicon-book">
    				<strong>Bookers</strong>
    				,
    			</span>
    		</p>
    		<p>
    			you can share and exchange your opinions, inpressions, and emotions
    		</p>
    		<p>
	            about various books!
            </p>
            <div class="btn-wrapper">
            	<div class="row">
            		<p>
            			<%= link_to "Log in", user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %>
            		</p>
            	</div>
            	<div class="row">
            		<p>
            			<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %>
            		</p>
            	</div>
            </div>
    	</div>
    </div>
</div>