config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#top'
  get 'home/about' => 'users#about', as: 'about_book'
  devise_for :users, controllers: {sessions: 'devise/sessions', 
  	registrations: 'devise/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:new, :create, :index, :show, :edit, :update]
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user, optional: true
	attachment :profile_image
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def user
		return User.find_by(id: self.user_id)
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, {only: [:index, :show, :edit, :update]}
  before_action :correct_user, {only: [:edit, :update]}

  def top
  end

  def new
  	@book = Book.new
  end

  def create
  	@book = Book.new(book_params)
  	@book.user_id = current_user.id
  	@books = Book.all
  	@user = current_user
  	if @book.save
  	 	flash[:notice] = "You have created book successfully."
  	    redirect_to book_path(@book.id)
  	else
  	 	render "index"
  	end
  end

  def index
  	@books = Book.all
  	@book = Book.new
  	@user = current_user
  	@users = User.all
  end

  def show
  	@book = Book.find(params[:id])
    @book_new = Book.new
    @user = current_user
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  	  flash[:notice] = "You have updated book successfully."
  	    redirect_to book_path(@book.id)
  	else
  	  render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path
  end

  private
  def book_params
  	params.require(:book).permit(:title, :body)
  end

  def correct_user
    book = Book.find(params[:id])
    if current_user != book.user
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<div class="error-box">
    <% if @book.errors.any? %>
      <div class="error-explain">
        <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li>
             <%= message %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
</div>

<%= form_for(@book) do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Opinion</h4>
    <%= f.text_area :body %>
    <div class="action">
      <%= f.submit 'Update Book' %>
    </div>
    <%= link_to "Show", book_path(@book.id) %>
    |
    <%= link_to "Back", books_path %>
<% end %>

app/views/books/index.html.erb
<% if flash[:notice] %>
   <div class="flash">
    <%= flash[:notice] %>
   </div>
<% end %>

<div class="error-box">
    <% if @book.errors.any? %>
      <div class="error-explain">
        <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li>
             <%= message %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
</div>

<div class="container">
  <div class="row">
   <div class="col-xs-3">
    <h1>User info</h1>
     <%= attachment_image_tag @user, :profile_image, :fill, 60,60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
     <table class="table">
       <tbody>
         <tr>
           <th>
             name
           </th>
           <th>
             <%= @user.name %>
           </th>
         </tr>
         <tr>
           <th>
             introduction
           </th>
           <th>
             <%= @user.introduction %>
           </th>
         </tr>
       </tbody>
     </table>
     <div class="row">
       <% if @user.id == current_user.id %>
           <%= link_to "", edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
       <% else %>
           <%= link_to "", user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
       <% end %>
     </div>

    <h1>New book</h1>
     <%= form_for(@book) do |f| %>
       <h4>Title</h4>
       <%= f.text_field :title %>

       <h4>Opinion</h4>
       <%= f.text_area :body %>

       <%= f.submit 'Create Book', class: "btn btn-primary btn-lg" %>
     <% end %>
   </div>
   <div class="col-xs-9">
   <h1>Books</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th align="left" colspan="1"></th>
          <th align="left">Title</th>
          <th align="left">Opinion</th>
        </tr>
      </thead>
      <tbody>
       <% @books.each do |book| %>
        <tr>
          <td><%= link_to attachment_image_tag(book.user, :profile_image, :fill, 60,60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg"), book.user %></td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
        </tr>
       <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>
<%= form_for(@book) do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Opinion</h4>
    <%= f.text_area :body %>

    <%= f.submit 'Create Book', class: "btn btn-primary btn-lg" %>
<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
   <div class="flash">
    <%= flash[:notice] %>
   </div>
<% end %>


<div class="container">
  <div class="row">
   <div class="col-xs-3">
    <h1>User info</h1>
     <%= attachment_image_tag @book.user, :profile_image, :fill, 60,60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
     <table class="table">
       <tbody>
         <tr>
           <th>
             name
           </th>
           <th>
             <%= @book.user.name %>
           </th>
         </tr>
         <tr>
           <th>
             introduction
           </th>
           <th>
             <%= @book.user.introduction %>
           </th>
         </tr>
       </tbody>
     </table>
     <div class="row">
       <% if @user.id == current_user.id %>
           <%= link_to "", edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
       <% else %>
           <%= link_to "", user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
       <% end %>
     </div>

    <h1>New book</h1>
     <%= form_for(@book_new) do |f| %>
       <h4>Title</h4>
       <%= f.text_field :title %>

       <h4>Opinion</h4>
       <%= f.text_area :body %>

       <%= f.submit 'Create Book', class: "btn btn-primary btn-lg" %>
     <% end %>

   </div>
   <div class="col-xs-9">
   <h1>Book detail</h1>
    <table class="table table-striped">
      <tbody>
        <tr>
          <td>
            <%= link_to @book.user do %>
             <div class="profile-image">
              <%= attachment_image_tag @book.user, :profile_image, :fill, 60,60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
             </div>
             <p><%= @book.user.name %></p>
            <% end %>
          </td>
          <td><%= @book.title %></td>
          <td><%= @book.body %></td>
          <% if @book.user.id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success btn-sm" %></td>
            <td><%= link_to "Destroy", destroy_book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-danger btn-sm" %></td>
          <% end %>
        </tr>
      </tbody>
    </table>
    </div>
  </div>
</div>