config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#top'
  get 'home/about' => 'users#about', as: 'about_book'
  devise_for :users, controllers: {sessions: 'devise/sessions', 
  	registrations: 'devise/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:new, :create, :index, :show, :edit, :update]
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  resources :users, only: [:index, :show, :edit, :update]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://kit.fontawesome.com/edb8a28ad6.js" crossorigin="anonymous"></script>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <h2>
            <font color="#ffffff">
              Bookers
            </font>
          </h2>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
           <% if user_signed_in? %>
            <li class="">
              <%= link_to user_path(current_user.id) do %>
                <i class="fas fa-home"></i>
                 Home
              <% end %>
            </li>
            <li class="">
              <%= link_to users_path do %>
                <i class="fas fa-user"></i>
                 Users
              <% end %>
            </li>
            <li class="">
              <%= link_to books_path do %>
                <i class="fas fa-book"></i>
                 Books
              <% end %>
            </li>
            <li class="">
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i>
                 Logout
              <% end %>
            </li>
           <% else %>
            <li class="">
              <%= link_to root_path do %>
                <i class="fas fa-home"></i>
                Home
              <% end %>
            </li>
            <li class="">
              <%= link_to about_book_path do %>
                <i class="fas fa-link"></i>
                 About
              <% end %>
            </li>
            <li class="">
              <%= link_to new_user_registration_path do %>
                <i class="fas fa-edit"></i>
                 sign up
              <% end %>
            </li>
            <li class="">
              <%= link_to user_session_path do %>
                <i class="fas fa-sign-in-alt"></i>
                 login
              <% end %>
            </li>
           <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="body">
      <%= yield %>
    </div>
  </body>
</html>